# Usa una imagen base de NGINX
FROM nginx:alpine

# Copia el archivo HTML estático al directorio de contenido de NGINX
COPY index.html /usr/share/nginx/html/

# Por defecto, NGINX expone el puerto 80, lo usaremos.
# El archivo index.html se copia y el contenedor está listo.
